# Generated by Django 3.1.3 on 2020-11-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyrecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddisease',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='adddisease',
            name='datepurchased',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='addmedication',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='addmedication',
            name='datepurchased',
            field=models.DateField(null=True),
        ),
    ]
