# Generated by Django 3.1.3 on 2020-11-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyrecords', '0002_auto_20201123_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddisease',
            name='dateAdded',
        ),
        migrations.RemoveField(
            model_name='adddisease',
            name='datepurchased',
        ),
        migrations.RemoveField(
            model_name='addmedication',
            name='dateAdded',
        ),
        migrations.RemoveField(
            model_name='addmedication',
            name='datepurchased',
        ),
    ]
