# Generated by Django 3.1.3 on 2020-11-14 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, null=True)),
                ('Phone', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('dateAdded', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Livestockname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, null=True)),
                ('description', models.TextField(null=True)),
                ('dateAdded', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('dateAdded', models.DateTimeField(auto_now_add=True, null=True)),
                ('datepurchased', models.DateField(null=True)),
                ('farmName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestockrecords.farmname')),
                ('livestockname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestockrecords.livestockname')),
            ],
            options={
                'ordering': ['-datepurchased'],
            },
        ),
    ]
