# Generated by Django 3.1.3 on 2020-11-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestockrecords', '0002_adddisease_addmedication_feeding_medication_motality'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Motality',
            new_name='Mortality',
        ),
    ]
