# Generated by Django 3.1.3 on 2020-11-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestockrecords', '0003_auto_20201117_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeding',
            name='livestock',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='livestock',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='mortality',
            name='livestock',
        ),
        migrations.DeleteModel(
            name='Adddisease',
        ),
        migrations.DeleteModel(
            name='Addmedication',
        ),
        migrations.DeleteModel(
            name='Feeding',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='Mortality',
        ),
    ]
